spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      username: admin
      password: admin
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5433/auth_service
server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
