services:
  registry-service:
    build:
      context: ./registry-service
    ports:
      - "8761:8761"
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - registry-service

  api-gateway:
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - registry-service

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
