global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'registry-service'
    static_configs:
      - targets: ['host.docker.internal:8761']

  - job_name: 'auth-service'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
