spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  h2:
    console:
      enabled: false
server:
  port: 8080
jwt:
  public:
    key: classpath:app.pub
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761
logging:
  level:
    io.micrometer: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
